# Generated by Django 3.1.5 on 2021-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art',
            field=models.ImageField(default='media/default.jpg', upload_to='media/art'),
        ),
    ]
