# Generated by Django 3.1.5 on 2021-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210126_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art',
            field=models.ImageField(default='avatar.jpeg', upload_to='art'),
        ),
    ]
