# Generated by Django 3.1.5 on 2021-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210126_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art',
            field=models.ImageField(default='profile_images/avatar.jpeg', upload_to='gallery_images'),
        ),
    ]
