# Generated by Django 3.1.5 on 2021-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210128_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art',
            field=models.ImageField(default='avatar.jpeg', upload_to='art'),
        ),
    ]
